[system]
description = "Simple system: the ping pong test for IPC, and initialization ordering"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "bt"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "new_component"
img  = "tests.new_component"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "bt"}]
baseaddr = "0x1600000"
constructor = "booter"